// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {controlFlowKeywords, specializeIdentifier} from "./ahk-v2.0.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!jQ]QROOOOQO'#Cd'#CdO!jQRO'#ChO!qQQO'#C}OOQP'#C}'#C}OOQP'#Ci'#CiQ]QROOOOQP,59S,59SO!vQRO,59SOOQP,59i,59iOOQP-E6g-E6gOOQP1G.n1G.n",
  stateData: "#Q~OpOSTOSUOS~OYSOZSO_PO`POaPObPOcPOdPOePOfPOgPOhPOiPOjPOkPOlPOmPOnPOsQO~OrVO~P]OXXO~OrZO~P]OZX~",
  goto: "!arPPPPPPPPsPPPy!PPPPPPPPPPPPPPPPPPPP!ZXROQUWXSOQUWQUOQWQTYUWXTOQUW",
  nodeNames: "⚠ BuiltinVariable BuiltinConstant BuiltinFunction BuiltinClass LineComment BlockComment Program ControlFlow Identifier String Boolean Application",
  maxTerm: 35,
  skippedNodes: [0,1,2,3,4,5,6],
  repeatNodeCount: 1,
  tokenData: "-}~RcXY!^YZ!^]^!^pq!^rs!owx$]xy%tyz%y}!O&O!P!Q&d!Q![&O!]!^)o!c!}&O#R#S&O#T#Y&O#Y#Z*W#Z#h&O#h#i,w#i#o&O~!cSp~XY!^YZ!^]^!^pq!^~!rVOr!ors#Xs#S!o#S#T#^#T;'S!o;'S;=`$V<%lO!o~#^OY~~#aRO;'S!o;'S;=`#j;=`O!o~#mWOr!ors#Xs#S!o#S#T#^#T;'S!o;'S;=`$V;=`<%l!o<%lO!o~$YP;=`<%l!o~$`VOw$]wx#Xx#S$]#S#T$u#T;'S$];'S;=`%n<%lO$]~$xRO;'S$];'S;=`%R;=`O$]~%UWOw$]wx#Xx#S$]#S#T$u#T;'S$];'S;=`%n;=`<%l$]<%lO$]~%qP;=`<%l$]~%yOs~~&OOr~~&TTX~}!O&O!Q![&O!c!}&O#R#S&O#T#o&O~&gPz{&j~&mTOz&jz{&|{;'S&j;'S;=`)Y;=`O&j~'PVOz&jz{&|{!P&j!P!Q'f!Q;'S&j;'S;=`)Y;=`O&j~'i[OX&jXY'fYZ(_Z]&j]^'f^p&jpq'fqz&jz{&|{;'S&j;'S;=`)Y;=`O&j~(d[U~OX&jXY'fYZ(_Z]&j]^'f^p&jpq'fqz&jz{&|{;'S&j;'S;=`)Y;=`O&j~)]UOz&jz{&|{;'S&j;'S;=`)Y;=`<%l&j<%lO&j~)tST~OY)oZ;'S)o;'S;=`*Q<%lO)o~*TP;=`<%l)o~*]UX~}!O&O!Q![&O!c!}&O#R#S&O#T#U*o#U#o&O~*tVX~}!O&O!Q![&O!c!}&O#R#S&O#T#`&O#`#a+Z#a#o&O~+`VX~}!O&O!Q![&O!c!}&O#R#S&O#T#g&O#g#h+u#h#o&O~+zVX~}!O&O!Q![&O!c!}&O#R#S&O#T#X&O#X#Y,a#Y#o&O~,hTZ~X~}!O&O!Q![&O!c!}&O#R#S&O#T#o&O~,|VX~}!O&O!Q![&O!c!}&O#R#S&O#T#f&O#f#g-c#g#o&O~-hVX~}!O&O!Q![&O!c!}&O#R#S&O#T#i&O#i#j+u#j#o&O",
  tokenizers: [controlFlowKeywords, 0],
  topRules: {"Program":[0,7]},
  specialized: [{term: 9, get: (value: any, stack: any) => (specializeIdentifier(value, stack) << 1), external: specializeIdentifier}],
  tokenPrec: 91
})
