// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeIdentifier} from "./ahk-v2.0.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQ]QPOOOkQPO'#ChOOQO'#Cm'#CmOOQO'#Ci'#CiQ]QPOOOOQO,59S,59SO|QPO,59SOOQO-E6g-E6gOOQO1G.n1G.n",
  stateData: "!b~O`OSSOSTOS~OVQOWQOXQOZPO~OVQOWQOXQOYTOZPO~OVQOWQOXQOYWOZPO~OXV~",
  goto: "ybPPPPPPPPPPPPciPPPsXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ BuiltinVariable BuiltinConstant BuiltinFunction LineComment BlockComment Program Identifier String Boolean ) ( Application",
  maxTerm: 17,
  nodeProps: [
    ["openedBy", 10,"("],
    ["closedBy", 11,")"]
  ],
  skippedNodes: [0,1,2,3,4,5],
  repeatNodeCount: 1,
  tokenData: "-}~RcXY!^YZ!^]^!^pq!^rs!owx$]xy%tyz%y}!O&O!P!Q&d!Q![&O!]!^)o!c!}&O#R#S&O#T#Y&O#Y#Z*W#Z#h&O#h#i,w#i#o&O~!cS`~XY!^YZ!^]^!^pq!^~!rVOr!ors#Xs#S!o#S#T#^#T;'S!o;'S;=`$V<%lO!o~#^OW~~#aRO;'S!o;'S;=`#j;=`O!o~#mWOr!ors#Xs#S!o#S#T#^#T;'S!o;'S;=`$V;=`<%l!o<%lO!o~$YP;=`<%l!o~$`VOw$]wx#Xx#S$]#S#T$u#T;'S$];'S;=`%n<%lO$]~$xRO;'S$];'S;=`%R;=`O$]~%UWOw$]wx#Xx#S$]#S#T$u#T;'S$];'S;=`%n;=`<%l$]<%lO$]~%qP;=`<%l$]~%yOZ~~&OOY~~&TTV~}!O&O!Q![&O!c!}&O#R#S&O#T#o&O~&gPz{&j~&mTOz&jz{&|{;'S&j;'S;=`)Y;=`O&j~'PVOz&jz{&|{!P&j!P!Q'f!Q;'S&j;'S;=`)Y;=`O&j~'i[OX&jXY'fYZ(_Z]&j]^'f^p&jpq'fqz&jz{&|{;'S&j;'S;=`)Y;=`O&j~(d[T~OX&jXY'fYZ(_Z]&j]^'f^p&jpq'fqz&jz{&|{;'S&j;'S;=`)Y;=`O&j~)]UOz&jz{&|{;'S&j;'S;=`)Y;=`<%l&j<%lO&j~)tSS~OY)oZ;'S)o;'S;=`*Q<%lO)o~*TP;=`<%l)o~*]UV~}!O&O!Q![&O!c!}&O#R#S&O#T#U*o#U#o&O~*tVV~}!O&O!Q![&O!c!}&O#R#S&O#T#`&O#`#a+Z#a#o&O~+`VV~}!O&O!Q![&O!c!}&O#R#S&O#T#g&O#g#h+u#h#o&O~+zVV~}!O&O!Q![&O!c!}&O#R#S&O#T#X&O#X#Y,a#Y#o&O~,hTX~V~}!O&O!Q![&O!c!}&O#R#S&O#T#o&O~,|VV~}!O&O!Q![&O!c!}&O#R#S&O#T#f&O#f#g-c#g#o&O~-hVV~}!O&O!Q![&O!c!}&O#R#S&O#T#i&O#i#j+u#j#o&O",
  tokenizers: [0],
  topRules: {"Program":[0,6]},
  specialized: [{term: 7, get: (value: any, stack: any) => (specializeIdentifier(value, stack) << 1), external: specializeIdentifier}],
  tokenPrec: 61
})
