// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  BuiltinVariable = 1,
  BuiltinConstant = 2,
  BuiltinFunction = 3,
  LineComment = 4,
  BlockComment = 5,
  Program = 6,
  Identifier = 7,
  String = 8,
  Boolean = 9
