import { BuiltinConstant, BuiltinFunction, BuiltinVariable } from "./ahk-v2.0.gen.terms";

export function specializeIdentifier(name: string) {
  if (builtinVariables.has(name.toLowerCase())) return BuiltinVariable;
  if (builtinConstants.has(name.toLowerCase())) return BuiltinConstant;
  if (builtinFunctions.has(name.toLowerCase())) return BuiltinFunction;

  return -1;
}

const builtinVariables = new Set([
  "a_workingdir",
  "a_scriptname",
  "a_listlines",
  "a_titlematchmode",
  "a_titlematchmodespeed",
  "a_detecthiddenwindows",
  "a_detecthiddentext",
  "a_fileencoding",
  "a_sendmode",
  "a_sendlevel",
  "a_storecapslockmode",
  "a_keydelay",
  "a_keyduration",
  "a_keydelayplay",
  "a_keydurationplay",
  "a_windelay",
  "a_controldelay",
  "a_menumaskkey",
  "a_mousedelay",
  "a_mousedelayplay",
  "a_defaultmousespeed",
  "a_coordmodetooltip",
  "a_coordmodepixel",
  "a_coordmodemouse",
  "a_coordmodecaret",
  "a_coordmodemenu",
  "a_regview",
  "a_allowmainwindow",
  "a_iconhidden",
  "a_icontip",
  "a_maxhotkeysperinterval",
  "a_hotkeyinterval",
  "a_hotkeymodifiertimeout",
  "a_clipboard",
  "a_index",
]);

const builtinConstants = new Set([
  "a_space",
  "a_tab",
  "a_args",
  "a_initialworkingdir",
  "a_scriptdir",
  "a_scriptfullpath",
  "a_scripthwnd",
  "a_linenumber",
  "a_linefile",
  "a_thisfunc",
  "a_ahkversion",
  "a_ahkpath",
  "a_iscompiled",
  "a_yyyy",
  "a_mm",
  "a_dd",
  "a_mmmm",
  "a_mmm",
  "a_dddd",
  "a_ddd",
  "a_wday",
  "a_yday",
  "a_yweek",
  "a_hour",
  "a_min",
  "a_sec",
  "a_msec",
  "a_now",
  "a_nowutc",
  "a_tickcount",
  "a_issuspended",
  "a_ispaused",
  "a_iscritical",
  "a_traymenu",
  "a_iconfile",
  "a_iconnumber",
  "a_timeidle",
  "a_timeidlephysical",
  "a_timeidlekeyboard",
  "a_timeidlemouse",
  "a_thishotkey",
  "a_priorhotkey",
  "a_priorkey",
  "a_timesincethishotkey",
  "a_timesincepriorhotkey",
  "a_endchar",
  "a_comspec",
  "a_temp",
  "a_osversion",
  "a_is64bitos",
  "a_ptrsize",
  "a_language",
  "a_computername",
  "a_username",
  "a_windir",
  "a_programfiles",
  "a_appdata",
  "a_appdatacommon",
  "a_desktop",
  "a_desktopcommon",
  "a_startmenu",
  "a_startmenucommon",
  "a_programs",
  "a_programscommon",
  "a_startup",
  "a_startupcommon",
  "a_mydocuments",
  "a_isadmin",
  "a_screenwidth",
  "a_screenheight",
  "a_screendpi",
  "a_cursor",
  "a_eventinfo",
  "a_lasterror",
  "a_loopfilename",
  "a_loopfileext",
  "a_loopfilepath",
  "a_loopfilefullpath",
  "a_loopfileshortpath",
  "a_loopfileshortname",
  "a_loopfiledir",
  "a_loopfiletimemodified",
  "a_loopfiletimecreated",
  "a_loopfiletimeaccessed",
  "a_loopfileattrib",
  "a_loopfilesize",
  "a_loopfilesizekb",
  "a_loopfilesizemb",
  "a_loopregname",
  "a_loopregtype",
  "a_loopregkey",
  "a_loopregtimemodified",
  "a_loopreadline",
  "a_loopfield",
]);

const builtinFunctions = new Set(["msgbox"]);
