// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  BuiltinVariable = 1,
  BuiltinConstant = 2,
  BuiltinFunction = 3,
  BuiltinClass = 4,
  LineComment = 5,
  BlockComment = 6,
  Program = 7,
  Identifier = 8,
  String = 9,
  Boolean = 10
