// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {specializeIdentifier} from "./ahk-v2.0.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQ]QPOOOkQPO'#CgOOQO'#Cl'#ClOOQO'#Ch'#ChQ]QPOOOOQO,59R,59RO|QPO,59ROOQO-E6f-E6fOOQO1G.m1G.m",
  stateData: "!b~O_OSTOSUOS~OWQOXQOYQObPO~OWQOXQOYQOaTObPO~OWQOXQOYQOaWObPO~OYW~",
  goto: "xaPPPPPPPPPPPbhPPPrXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ BuiltinVariable BuiltinConstant BuiltinFunction BuiltinClass LineComment BlockComment Program Identifier String Boolean Application",
  maxTerm: 18,
  skippedNodes: [0,1,2,3,4,5,6],
  repeatNodeCount: 1,
  tokenData: "-}~RcXY!^YZ!^]^!^pq!^rs!owx$]xy%tyz%y}!O&O!P!Q&d!Q![&O!]!^)o!c!}&O#R#S&O#T#Y&O#Y#Z*W#Z#h&O#h#i,w#i#o&O~!cS_~XY!^YZ!^]^!^pq!^~!rVOr!ors#Xs#S!o#S#T#^#T;'S!o;'S;=`$V<%lO!o~#^OX~~#aRO;'S!o;'S;=`#j;=`O!o~#mWOr!ors#Xs#S!o#S#T#^#T;'S!o;'S;=`$V;=`<%l!o<%lO!o~$YP;=`<%l!o~$`VOw$]wx#Xx#S$]#S#T$u#T;'S$];'S;=`%n<%lO$]~$xRO;'S$];'S;=`%R;=`O$]~%UWOw$]wx#Xx#S$]#S#T$u#T;'S$];'S;=`%n;=`<%l$]<%lO$]~%qP;=`<%l$]~%yOb~~&OOa~~&TTW~}!O&O!Q![&O!c!}&O#R#S&O#T#o&O~&gPz{&j~&mTOz&jz{&|{;'S&j;'S;=`)Y;=`O&j~'PVOz&jz{&|{!P&j!P!Q'f!Q;'S&j;'S;=`)Y;=`O&j~'i[OX&jXY'fYZ(_Z]&j]^'f^p&jpq'fqz&jz{&|{;'S&j;'S;=`)Y;=`O&j~(d[U~OX&jXY'fYZ(_Z]&j]^'f^p&jpq'fqz&jz{&|{;'S&j;'S;=`)Y;=`O&j~)]UOz&jz{&|{;'S&j;'S;=`)Y;=`<%l&j<%lO&j~)tST~OY)oZ;'S)o;'S;=`*Q<%lO)o~*TP;=`<%l)o~*]UW~}!O&O!Q![&O!c!}&O#R#S&O#T#U*o#U#o&O~*tVW~}!O&O!Q![&O!c!}&O#R#S&O#T#`&O#`#a+Z#a#o&O~+`VW~}!O&O!Q![&O!c!}&O#R#S&O#T#g&O#g#h+u#h#o&O~+zVW~}!O&O!Q![&O!c!}&O#R#S&O#T#X&O#X#Y,a#Y#o&O~,hTY~W~}!O&O!Q![&O!c!}&O#R#S&O#T#o&O~,|VW~}!O&O!Q![&O!c!}&O#R#S&O#T#f&O#f#g-c#g#o&O~-hVW~}!O&O!Q![&O!c!}&O#R#S&O#T#i&O#i#j+u#j#o&O",
  tokenizers: [0],
  topRules: {"Program":[0,7]},
  specialized: [{term: 8, get: (value: any, stack: any) => (specializeIdentifier(value, stack) << 1), external: specializeIdentifier}],
  tokenPrec: 61
})
